
services:
    app:
        container_name: ${COMPOSE_PROJECT_NAME}_php_fpm
        build:
            context: "./php"
            dockerfile: "Dockerfile"
            target: base
        restart: always
        working_dir: /app
        volumes:
            - "../src:/app"
        networks:
            - project_net

    nginx:
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        image: nginx:latest
        restart: always
        volumes:
            - "./nginx:/etc/nginx/conf.d"
            - "../src:/app"
        networks:
            - project_net

networks:
    project_net:
        name: ${COMPOSE_PROJECT_NAME}_network
